In [1]:
from numpy import linalg as LA
import os
import pandas as pd
import numpy as np
from scipy.signal import find_peaks_cwt
import pickle
from pathlib import Path
from scipy.stats import kurtosis, skew
from scipy.stats import iqr
from pyentrp import entropy as ent
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import precision_score, recall_score, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import normalize
import sys
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
import matplotlib.pyplot as plt

%matplotlib inline

## Compute features for accelerometer only

In [6]:
#Helper Functions

def Signal_magnitude_area(x,y,z):
    
    sum = 0    
    for i in range(len(x)):
        sum += (abs(x[i]) + abs(y[i]) + abs(z[i]))
        
    return float(sum)/len(x)


def Power(x):
    
    power = (LA.norm(x)**2)/ len(x)
    return power
    
def number_of_peaks(window):
    indexes = find_peaks_cwt(window, np.arange(1, len(window)))

    return len(indexes)

#this function assumes that records are evenly spaced
def trim_first_last_n_seconds(df, n, freq):
    if df.shape[0] < 6001:
        return None
    
    remove_indexes = list(range(0, int(n*1000/freq)))
    df = df.drop(remove_indexes)

    remove_indexes = list(range(df.shape[0] - int(n*1000/freq), df.shape[0]-1))
    df = df.drop(remove_indexes)
    
    return df
    
def load_files(indir,pickles_indir):
    trim_num_seconds = 10
    acc_freq = 4
    window_num_seconds = 4 #seconds
    steps_per_sec = int(1000/acc_freq)
    window_size = 10#int(window_num_seconds*steps_per_sec)
    window_step = 2 #seconds
    window_jump_steps = 5#int(window_step*steps_per_sec)
    dfs_list = []
    features = []
    labels = []
    bypass = True
    pickle_file = Path(pickles_indir+"/img_accelerometer_features.pickle")
    
    if pickle_file.exists():
        print("Found pickle files for accelerometer")
        features = pickle.load(open(pickles_indir+"/img_accelerometer_features.pickle", "rb"))
        labels = pickle.load(open(pickles_indir+"/img_accelerometer_labels.pickle", "rb"))
        dfs_list = pickle.load(open(pickles_indir+"/img_accelerometer_dfs_list.pickle", "rb"))

    else:

        for root, dirs, files in os.walk(indir):
            path = root.split(os.sep)
            for f in files:
                print("/".join(path) + "/" + f)
                full_path = "/".join(path) + "/" + f
                if "gyroscope" in full_path:
                    print("Skip ", full_path)
                    continue
                df = pd.read_csv(full_path, header=None)

                print("Before trimming: ", df.shape)

                df = trim_first_last_n_seconds(df, trim_num_seconds, acc_freq)
                if df is None:
                    print("Continuing")
                    continue

                print("After trimming: ", df.shape)

                #Sample the data according to the size of the window with 50% overlap
                for index in range(0, df.shape[0]-window_size, window_jump_steps):
                    indexes = list(range(index, index + int(window_size)))

                    window = df.iloc[indexes,:]

                    X_list = window[1].tolist()
                    Y_list = window[2].tolist()
                    Z_list = window[3].tolist()


                    #Generate the features for this window


           # ****************** Time-Domain Features ************************* #

                    #Mean of the signals
                    mean_x = np.mean(X_list)
                    mean_y = np.mean(Y_list)
                    mean_z = np.mean(Z_list)

                    #Variance of the signals
                    var_x = np.var(X_list)
                    var_y = np.var(Y_list)
                    var_z = np.var(Z_list)

                    #Number of peaks in the signals
                    #num_peaks_x = number_of_peaks(X_list)
                    #num_peaks_y = number_of_peaks(Y_list)
                    #num_peaks_z = number_of_peaks(Z_list)            

                    #Median of the signals
                    median_x = np.ma.median(X_list)
                    median_y = np.ma.median(Y_list)
                    median_z = np.ma.median(Z_list)

                    #Standard Deviation of the signals
                    std_x = np.std(X_list)
                    std_y = np.std(Y_list)
                    std_z = np.std(Z_list)

                    #Compute Signal Magnitude Area
                    signal_mag_area = Signal_magnitude_area(X_list, Y_list, Z_list)

                    #Maximum and Minimum values and their indexes
                    max_x = max(X_list)
                    max_index_x = X_list.index(max_x)               
                    min_x = min(X_list)
                    min_index_x = X_list.index(min_x)

                    max_y = max(Y_list)
                    max_index_y = Y_list.index(max_y)              
                    min_y = min(Y_list)
                    min_index_y = Y_list.index(min_y)               

                    max_z = max(Z_list)
                    max_index_z = Z_list.index(max_z)             
                    min_z = min(Z_list)
                    min_index_z = Z_list.index(min_z)


                    #Power of X,Y and Z signals             
                    power_x = Power(X_list)
                    power_y = Power(Y_list)
                    power_z = Power(Z_list)


                    #Skewness and Kurtosis
                    skew_x = skew(X_list)
                    skew_y = skew(Y_list)
                    skew_z = skew(Z_list)

                    kurtosis_x = kurtosis(X_list)                
                    kurtosis_y = kurtosis(Y_list)
                    kurtosis_z = kurtosis(Z_list)


                    #Entropy of the signals (Can experiment with different types of Entropy)
                    entropy_x = ent.shannon_entropy(X_list)
                    entropy_y = ent.shannon_entropy(Y_list)
                    entropy_z = ent.shannon_entropy(Z_list)


                    #Interquartile range of the signals
                    iqr_x = iqr(X_list)
                    iqr_y = iqr(Y_list)
                    iqr_z = iqr(Z_list)


        # ****************** Frequency-Domain Features ************************* #

                    #Normalized FFT coefficients
                    fft_x = LA.norm(np.fft.rfft(X_list))              
                    fft_y = LA.norm(np.fft.rfft(Y_list))   
                    fft_z = LA.norm(np.fft.rfft(Z_list))  


                    #Store the features
                    window_feature = []
                    window_feature.append(mean_x)
                    window_feature.append(mean_y)
                    window_feature.append(mean_z)

                    window_feature.append(var_x)
                    window_feature.append(var_y)
                    window_feature.append(var_z)

                    window_feature.append(median_x)
                    window_feature.append(median_y)
                    window_feature.append(median_z)

                    window_feature.append(std_x)
                    window_feature.append(std_y)
                    window_feature.append(std_z)


                    window_feature.append(signal_mag_area)

                    window_feature.append(max_x)
                    window_feature.append(max_index_x)
                    window_feature.append(min_x)
                    window_feature.append(min_index_x)

                    window_feature.append(max_y)
                    window_feature.append(max_index_y)
                    window_feature.append(min_y)
                    window_feature.append(min_index_y)

                    window_feature.append(max_z)
                    window_feature.append(max_index_z)
                    window_feature.append(min_z)
                    window_feature.append(min_index_z)

                    window_feature.append(power_x)
                    window_feature.append(power_y)
                    window_feature.append(power_z)

                    window_feature.append(skew_x)
                    window_feature.append(kurtosis_x) 

                    window_feature.append(skew_y)
                    window_feature.append(kurtosis_y) 

                    window_feature.append(skew_z)
                    window_feature.append(kurtosis_z) 

                    window_feature.append(entropy_x)
                    window_feature.append(entropy_y)
                    window_feature.append(entropy_z)

                    window_feature.append(iqr_x)
                    window_feature.append(iqr_y)
                    window_feature.append(iqr_z)

                    window_feature.append(fft_x)
                    window_feature.append(fft_y)
                    window_feature.append(fft_z)


                    #window_feature.append(num_peaks_x)
                    #window_feature.append(num_peaks_y)
                    #window_feature.append(num_peaks_z)

                    #scale = preprocessing.minmax_scale(data, feature_range=(-0.5, 0.5))

                    features.append(window_feature)

                    labels.append(df[5].iloc[1])
                dfs_list.append(df)
        dfs = pd.concat(dfs_list)
        if not os.path.exists(pickles_indir):
            os.mkdir(pickles_indir)
        pickle.dump(features, open(pickles_indir+"/img_accelerometer_features.pickle", "wb"), protocol=2)
        pickle.dump(labels, open(pickles_indir+"/img_accelerometer_labels.pickle", "wb"), protocol=2)
        pickle.dump(dfs_list, open(pickles_indir+"/img_accelerometer_dfs_list.pickle", "wb"), protocol=2)

    features = np.asarray(features)
    labels = np.asarray(labels)
    return features, labels

### Loading test and train features from appropriate directories

In [ ]:
print('loading train')
features_train, labels_train = load_files(indir='data_3_8_2018',pickles_indir='img_pickles_train')
print('loading test')
features_test, labels_test = load_files(indir='test3',pickles_indir='img_pickles_test')

loading train
data_3_8_2018/0_1_android.sensor.accelerometer.data.csv
('Before trimming: ', (40642, 6))
('After trimming: ', (35643, 6))
data_3_8_2018/0_4_android.sensor.gyroscope.data.csv
('Skip ', 'data_3_8_2018/0_4_android.sensor.gyroscope.data.csv')
data_3_8_2018/10_1_android.sensor.accelerometer.data.csv
('Before trimming: ', (137412, 6))
('After trimming: ', (132413, 6))
data_3_8_2018/10_4_android.sensor.gyroscope.data.csv
('Skip ', 'data_3_8_2018/10_4_android.sensor.gyroscope.data.csv')
data_3_8_2018/11_1_android.sensor.accelerometer.data.csv
('Before trimming: ', (100066, 6))
('After trimming: ', (95067, 6))
data_3_8_2018/11_4_android.sensor.gyroscope.data.csv
('Skip ', 'data_3_8_2018/11_4_android.sensor.gyroscope.data.csv')
data_3_8_2018/12_1_android.sensor.accelerometer.data.csv
('Before trimming: ', (64964, 6))
('After trimming: ', (59965, 6))
data_3_8_2018/12_4_android.sensor.gyroscope.data.csv
('Skip ', 'data_3_8_2018/12_4_android.sensor.gyroscope.data.csv')
data_3_8_2018/

data_3_8_2018/40_4_android.sensor.gyroscope.data.csv
('Skip ', 'data_3_8_2018/40_4_android.sensor.gyroscope.data.csv')
data_3_8_2018/41_1_android.sensor.accelerometer.data.csv
('Before trimming: ', (67641, 6))
('After trimming: ', (62642, 6))
data_3_8_2018/41_4_android.sensor.gyroscope.data.csv
('Skip ', 'data_3_8_2018/41_4_android.sensor.gyroscope.data.csv')
data_3_8_2018/42_1_android.sensor.accelerometer.data.csv
('Before trimming: ', (40200, 6))
('After trimming: ', (35201, 6))
data_3_8_2018/42_4_android.sensor.gyroscope.data.csv
('Skip ', 'data_3_8_2018/42_4_android.sensor.gyroscope.data.csv')
data_3_8_2018/43_1_android.sensor.accelerometer.data.csv
('Before trimming: ', (118805, 6))
('After trimming: ', (113806, 6))
data_3_8_2018/43_4_android.sensor.gyroscope.data.csv
('Skip ', 'data_3_8_2018/43_4_android.sensor.gyroscope.data.csv')
data_3_8_2018/44_1_android.sensor.accelerometer.data.csv
('Before trimming: ', (65634, 6))
('After trimming: ', (60635, 6))
data_3_8_2018/44_4_android

In [ ]:
## Using LDA to reduce the fimensions into 3 

In [61]:
labels_copy_train = labels_train
labels_copy_test = labels_test
features_copy_train = features_labels_train
features_copy_test = features_test

In [68]:
print(features_train.shape)
print(labels_train.shape)
print(features_test.shape)
print(labels_test.shape)

(1183508, 1)
(1183508,)
(166181, 1)
(166181,)


In [62]:
labels_copy_train = ['not_walking' if not x=='walking' else 'walking' for x in labels_copy_train]
labels_copy_test = ['not_walking' if not x=='walking' else 'walking' for x in labels_copy_test]
print(np.unique(labels_copy_test))
print(np.unique(labels_copy_train))

['not_walking' 'walking']
['not_walking' 'walking']


In [63]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components=3)

In [66]:
features_train = lda.fit(features_train, np.asarray(labels_copy_train)).transform(features_train)
features_test = lda.transform(features_test)

In [67]:
print(features_train.shape)
print(labels_train.shape)
print(features_test.shape)
print(labels_test.shape)

(1183508, 1)
(1183508,)
(166181, 1)
(166181,)


## Put the train and test features into dataframe

In [50]:
features_df_train = pd.DataFrame(features_train,columns=['a','b','c'])
labels_df_train = pd.DataFrame(labels_copy_train,columns=['l'])
features_df_test = pd.DataFrame(features_test,columns=['a','b','c'])
labels_df_test = pd.DataFrame(labels_copy_test,columns=['l'])

In [49]:
print(np.unique(labels_copy_test))

['not_walking' 'walking']


In [51]:
features_df_train['l'] = labels_df_train['l']
features_df_test['l'] = labels_df_test['l']

In [15]:
activities = ['walking','sitting','standing','laying_down']

In [52]:
activities =['walking','not_walking']

## Findind the minimum and maximum using 1 stddev away from mean

In [53]:
max_=[]
min_=[]
for axis in ['a','b','c']:
    print('axis',axis)
    mean =np.mean(features_df_train[axis])
    std =np.std(features_df_train[axis]) 
    print(mean,std)
    print(np.min(features_df_train[axis]),np.max(features_df_train[axis]))
    max_.append(mean+2*std)
    min_.append(mean-2*std)
    #max_.append()        


('axis', 'a')
(5.7716215347198105e-12, 1.91922926997777)
(-31.62189545806002, 10.543340943243994)
('axis', 'b')
(-7.77187738633384e-13, 1.2881504023883437)
(-32.04581690335029, 14.01614505360675)
('axis', 'c')
(1.6091897214039542e-13, 1.1460491956299006)
(-38.524362911029634, 8.237474300465975)


In [54]:
max_

[3.838458539961312, 2.57630080477591, 2.292098391259962]

In [55]:
min_

[-3.838458539949768, -2.5763008047774645, -2.2920983912596404]

## Functions to scale features from feature values to colrs

In [19]:
def get_color(i,num):
    scale_ = 255 /(max_[i]-min_[i])
    num = max(min_[i],num)
    num = min(num,max_[i])
    return (num - min_[i])*scale_
def get_rgb(feature):
    #print(feature)
    feature = list(feature)
    #print(feature)
    col = []
    for i in range(0,3):
        col.append(int(get_color(i,feature[i])))
    #col[1] = 0
    return col
    

In [20]:
def spiral(lst,n):
    dx,dy = 1,0            # Starting increments
    x,y = 0,0              # Starting location
    myarray = [[None]* n for j in range(n)]
    for i in range(n**2):
        myarray[x][y] = lst[i]
        nx,ny = x+dx, y+dy
        if 0<=nx<n and 0<=ny<n and myarray[nx][ny] == None:
            x,y = nx,ny
        else:
            dx,dy = -dy,dx
            x,y = x+dx, y+dy
    return myarray

## Features converted to 0 - 255

In [21]:
array_map_train={}
array_map_test={}
for activity in activities:
    print('train')
    df = features_df_train[features_df_train['l']==activity][['a','b','c']].copy()
    print(df.shape)
    array_map_train[activity] = (df.as_matrix())
    print((array_map_train[activity][2]))
    print('test')
    df = features_df_test[features_df_test['l']==activity][['a','b','c']].copy()
    print(df.shape)
    array_map_test[activity] = (df.as_matrix())
    print((array_map_test[activity][2]))
    

train
(317822, 3)
[ 1.43134746 -0.73815934  1.62548252]
test
(18856, 3)
[ 2.84198523 -0.75064632 -1.39818406]
train
(286720, 3)
[-1.93302792 -0.16730912  0.66142161]
test
(46629, 3)
[ 0.79655389 -1.03309884 -0.95708547]
train
(276870, 3)
[ 2.13052628 -0.95745858 -1.30124221]
test
(17313, 3)
[-1.12413381  1.21064526 -2.36662753]
train
(302096, 3)
[-1.6907363   4.01332736 -1.46883218]
test
(83383, 3)
[-0.06396953 -0.47449681  0.09974866]


In [22]:
color_map_train = {}
color_map_test = {}
for activity in activities:
    color_map_train[activity] = [get_rgb(x) for x in array_map_train[activity]]
    print(color_map_train[activity][1])
    color_map_test[activity] = [get_rgb(x) for x in array_map_test[activity]]
    print(color_map_test[activity][1])

[187, 79, 205]
[241, 118, 99]
[54, 122, 166]
[126, 85, 74]
[200, 80, 65]
[83, 191, 0]
[64, 255, 37]
[120, 117, 146]


## Coverting to square images

In [23]:
from collections import defaultdict
color_map_spiral_train = defaultdict(list)
color_map_spiral_test = defaultdict(list)
for activity in activities:
    print(activity)
    siz = len(color_map_train[activity])
    for i in range((siz/625)-1):
        sp = spiral(color_map_train[activity][i*625:(i+1)*625],25)
        color_map_spiral_train[activity].append(sp)
    print(len(color_map_spiral_train[activity]))
    siz = len(color_map_test[activity])
    for i in range((siz/625)-1):
        sp = spiral(color_map_test[activity][i*625:(i+1)*625],25)
        color_map_spiral_test[activity].append(sp)
    print(len(color_map_spiral_test[activity]))    

walking
507
29
sitting
457
73
standing
441
26
laying_down
482
132


## Storing the images

In [24]:
from PIL import Image
import numpy as np

In [25]:
train_dir = 'img_train'
test_dir = 'img_test'
if not os.path.exists(train_dir):
    os.makedirs(train_dir)
if not os.path.exists(test_dir):
    os.makedirs(test_dir)

for activity in activities:
    i=0
    print(activity)
    if not os.path.exists(train_dir+'/'+activity):
        os.mkdir(train_dir+'/'+activity)        
    if not os.path.exists(test_dir+'/'+activity):
        os.mkdir(test_dir+'/'+activity)
        
    for spir_arr in color_map_spiral_train[activity]:
        i+=1
        img = Image.fromarray(np.array(spir_arr), 'RGB')
        img.save(train_dir+'/'+activity+'/'+activity+str(i)+'.png')
    
    for spir_arr in color_map_spiral_test[activity]:
        i+=1
        img = Image.fromarray(np.array(spir_arr), 'RGB')
        img.save(test_dir+'/'+activity+'/'+activity+str(i)+'.png')


walking
sitting
standing
laying_down


# TEST

In [26]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras import backend as K

# dimensions of our images.
img_width, img_height = 25, 25

train_data_dir = 'img_train'
validation_data_dir = 'img_test'
test_data_dir = 'img_test'

nb_train_samples = 1711
nb_validation_samples = 178
epochs = 50
batch_size = 16

if K.image_data_format() == 'channels_first':
    input_shape = (3, img_width, img_height)
else:
    input_shape = (img_width, img_height, 3)

    
model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=input_shape))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(32))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(4))
model.add(Activation('sigmoid'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])


# this is the augmentation configuration we will use for training
train_datagen = ImageDataGenerator(
    rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

# this is the augmentation configuration we will use for testing:
# only rescaling
test_datagen = ImageDataGenerator(rescale=1. / 255)

train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical')

validation_generator = test_datagen.flow_from_directory(
    validation_data_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical')

model.fit_generator(
    train_generator,
    steps_per_epoch=nb_train_samples // batch_size,
    epochs=epochs,
    validation_data=validation_generator,
    validation_steps=nb_validation_samples // batch_size)

model.save_weights('first_try.h5')

/anaconda/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


Found 1887 images belonging to 4 classes.
Found 260 images belonging to 4 classes.
Epoch 1/50
106/106 [==============================] - 3s 25ms/step - loss: 1.2271 - acc: 0.4178 - val_loss: 0.8104 - val_acc: 0.6477
Epoch 2/50
106/106 [==============================] - 2s 19ms/step - loss: 0.9216 - acc: 0.6124 - val_loss: 0.7832 - val_acc: 0.6477
Epoch 3/50
106/106 [==============================] - 2s 19ms/step - loss: 0.7771 - acc: 0.7086 - val_loss: 0.7990 - val_acc: 0.6420
Epoch 4/50
106/106 [==============================] - 2s 19ms/step - loss: 0.7209 - acc: 0.7446 - val_loss: 0.7118 - val_acc: 0.6477
Epoch 5/50
106/106 [==============================] - 2s 18ms/step - loss: 0.6789 - acc: 0.7482 - val_loss: 0.6538 - val_acc: 0.6648
Epoch 6/50
106/106 [==============================] - 2s 18ms/step - loss: 0.6732 - acc: 0.7576 - val_loss: 0.7039 - val_acc: 0.6364
Epoch 7/50
106/106 [==============================] - 2s 19ms/step - loss: 0.6427 - acc: 0.7723 - val_loss: 0.7238 - va

In [27]:
label_map = (train_generator.class_indices)
label_map

{'laying_down': 0, 'sitting': 1, 'standing': 2, 'walking': 3}

In [28]:
test_data_dir = 'img_test'

test_generator = test_datagen.flow_from_directory(
    test_data_dir,
    target_size=(img_width, img_height),
    #batch_size=batch_size,
    class_mode='categorical')

filenames = test_generator.filenames
nb_samples = len(filenames)

predict = model.predict_generator(test_generator)

Found 260 images belonging to 4 classes.


In [29]:
train_generator.filenames

['laying_down/laying_down1.png',
 'laying_down/laying_down10.png',
 'laying_down/laying_down100.png',
 'laying_down/laying_down101.png',
 'laying_down/laying_down102.png',
 'laying_down/laying_down103.png',
 'laying_down/laying_down104.png',
 'laying_down/laying_down105.png',
 'laying_down/laying_down106.png',
 'laying_down/laying_down107.png',
 'laying_down/laying_down108.png',
 'laying_down/laying_down109.png',
 'laying_down/laying_down11.png',
 'laying_down/laying_down110.png',
 'laying_down/laying_down111.png',
 'laying_down/laying_down112.png',
 'laying_down/laying_down113.png',
 'laying_down/laying_down114.png',
 'laying_down/laying_down115.png',
 'laying_down/laying_down116.png',
 'laying_down/laying_down117.png',
 'laying_down/laying_down118.png',
 'laying_down/laying_down119.png',
 'laying_down/laying_down12.png',
 'laying_down/laying_down120.png',
 'laying_down/laying_down121.png',
 'laying_down/laying_down122.png',
 'laying_down/laying_down123.png',
 'laying_down/laying_down

In [30]:
y_test = [[1,0,0,0]]*len(color_map_spiral_test['laying_down'])+[[0,1,0,0]]*len(color_map_spiral_test['sitting'])+[[0,0,1,0]]*len(color_map_spiral_test['standing'])+[[0,0,0,1]]*len(color_map_spiral_test['walking'])

In [32]:
#print predict

def get_hot_value(my_list):
        max_val = max(my_list)
        return [int(item == max_val) for item in my_list]

hot_list = [get_hot_value(sublist) for sublist in predict]

t  = np.array(y_test)
p  = np.array(hot_list)
t = np.argmax(t, axis=1)
p = np.argmax(p, axis=1)

#print hot_list
print("Precision: ", precision_score(t, p, average=None))

from sklearn.metrics import accuracy_score
print accuracy_score(t, p)

('Precision: ', array([0.52447552, 0.3       , 0.15517241, 0.17241379]))
0.3769230769230769


In [33]:
print len(predict)
print len(y_test)

260
260


In [34]:
predict

array([[5.8263022e-01, 2.1142463e-04, 4.8962765e-04, 1.3432278e-07],
       [3.8309439e-11, 7.4328858e-07, 7.5000443e-04, 9.8710746e-01],
       [9.7089862e-12, 3.1170958e-07, 3.5227789e-04, 9.9163377e-01],
       ...,
       [4.5429063e-01, 2.1466911e-02, 9.0691159e-03, 1.7716477e-04],
       [2.2617425e-03, 3.3544909e-02, 5.5353034e-01, 4.0908030e-04],
       [5.2583563e-01, 1.3020625e-03, 1.6373862e-03, 2.6909156e-06]],
      dtype=float32)

In [ ]:
hot_list